sudo: required
services: 
    - docker 

before_install:
    - docker build -t vbhvkas18/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true vbhvkas18/react-test npm test
after_success:
    - docker build -t vbhvkas18/multi-client ./client   
    - docker build -t vbhvkas18/multi-nginx ./nginx
    - docker build -t vbhvkas18/multi-server ./server
    - docker build -t vbhvkas18/multi-worker ./worker
    # Log in to the Docker CLI
    - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to Docker Hub
    - docker push vbhvkas18/multi-client
    - docker push vbhvkas18/multi-nginx
    - docker push vbhvkas18/multi-server
    - docker push vbhvkas18/multi-worker